apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "simple-web-dar.fullname" . }}
spec:
  scaleTargetRef:
    name: {{ include "simple-web-dar.fullname" . }}
  pollingInterval: {{.Values.keda.pollingInterval}}
  cooldownPeriod: {{.Values.keda.cooldownPeriod}}
  minReplicaCount: 1
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: {{.Values.keda.cpuValue}}
  - type: memory
    metadata:
      type: Utilization
      value: {{.Values.keda.memoryValue}}
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 8 * * *
      end: 0 12 * * *